run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gocyclo:
    min-complexity: 15
  
  govet:
    enable:
      - shadow
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: vn
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  unparam:
    check-exported: false
  
  gosec:
    severity: medium
    confidence: medium
  
  lll:
    line-length: 120

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  
  disable:
    - gochecknoglobals
    - gocognit
    - godox
    - godot
    - testpackage
    - gochecknoinits
    - dupl
    - depguard
    - funlen

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
    
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
    
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
    
    # Exclude errcheck for CLI flag parsing
    - path: cmd/
      linters:
        - errcheck
      text: "Error return value of.*GetString.*is not checked"
    
    - path: cmd/
      linters:
        - errcheck
      text: "Error return value of.*GetStringSlice.*is not checked"
    
    - path: cmd/
      linters:
        - errcheck
      text: "Error return value of.*GetInt.*is not checked"
    
    # Exclude errcheck for viper.BindPFlag which rarely fails
    - path: cmd/
      linters:
        - errcheck
      text: "Error return value of.*viper.BindPFlag.*is not checked"
    
    # Exclude gosec for color printing (cosmetic errors)
    - path: cmd/
      linters:
        - gosec
      text: "G104.*color.*Print"
    
    # Exclude gosec G204 in test files (subprocess execution is controlled)
    - path: tests/integration/cli_test\.go
      linters:
        - gosec
      text: "G204"
    
    # Exclude errcheck for test helpers and HTTP writes
    - path: internal/testutil/
      linters:
        - errcheck
    
    # Exclude magic numbers for common values
    - linters:
        - mnd
      text: "Magic number: 2,"
    
    - linters:
        - mnd
      text: "Magic number: 5,"
    
    - linters:
        - mnd
      text: "Magic number: 10,"
    
    - linters:
        - mnd
      text: "Magic number: 15,"
    
    - linters:
        - mnd
      text: "Magic number: 60,"
    
    - linters:
        - mnd
      text: "Magic number: 100,"

  max-issues-per-linter: 0
  max-same-issues: 0 